"""Output writing utilities for xcat.

This module owns the final output destination.

It decides whether xcat writes the generated text to stdout or to a file.
It should not scan paths, format file blocks, or resolve ignore patterns.
"""

import sys
from pathlib import Path


def configure_stdout() -> None:
    """Configure stdout to use UTF-8 when supported.

    This is especially useful on Windows, where the default console encoding
    may not be UTF-8.
    """
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]


def write_output(
    output: str, output_path: Path | None, force: bool = False
) -> None:
    """Write output to stdout or to a file.

    Args:
        output: Text generated by xcat.
        output_path: Optional destination file path. If None, output is written
            to stdout.
        force: Whether to overwrite an existing output file.

    Raises:
        FileExistsError: If output_path exists and force is False.
    """
    if output_path is None:
        print(output)
        return

    if output_path.exists() and not force:
        raise FileExistsError(
            f"output file already exists: {output_path}\n"
            "hint: pass -f/--force to overwrite it"
        )

    output_path.write_text(output, encoding="utf-8")
